// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrachaMessage_Stage int32

const (
	BrachaMessage_INITIAL BrachaMessage_Stage = 0
	BrachaMessage_ECHO    BrachaMessage_Stage = 1
	BrachaMessage_READY   BrachaMessage_Stage = 2
)

// Enum value maps for BrachaMessage_Stage.
var (
	BrachaMessage_Stage_name = map[int32]string{
		0: "INITIAL",
		1: "ECHO",
		2: "READY",
	}
	BrachaMessage_Stage_value = map[string]int32{
		"INITIAL": 0,
		"ECHO":    1,
		"READY":   2,
	}
)

func (x BrachaMessage_Stage) Enum() *BrachaMessage_Stage {
	p := new(BrachaMessage_Stage)
	*p = x
	return p
}

func (x BrachaMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrachaMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (BrachaMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x BrachaMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrachaMessage_Stage.Descriptor instead.
func (BrachaMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0}
}

type ConsistentProtocolMessage_Stage int32

const (
	ConsistentProtocolMessage_ECHO   ConsistentProtocolMessage_Stage = 0
	ConsistentProtocolMessage_VERIFY ConsistentProtocolMessage_Stage = 1
)

// Enum value maps for ConsistentProtocolMessage_Stage.
var (
	ConsistentProtocolMessage_Stage_name = map[int32]string{
		0: "ECHO",
		1: "VERIFY",
	}
	ConsistentProtocolMessage_Stage_value = map[string]int32{
		"ECHO":   0,
		"VERIFY": 1,
	}
)

func (x ConsistentProtocolMessage_Stage) Enum() *ConsistentProtocolMessage_Stage {
	p := new(ConsistentProtocolMessage_Stage)
	*p = x
	return p
}

func (x ConsistentProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistentProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ConsistentProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ConsistentProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistentProtocolMessage_Stage.Descriptor instead.
func (ConsistentProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5, 0}
}

type ReliableProtocolMessage_Stage int32

const (
	ReliableProtocolMessage_NOTIFY             ReliableProtocolMessage_Stage = 0
	ReliableProtocolMessage_ECHO_FROM_WITNESS  ReliableProtocolMessage_Stage = 1
	ReliableProtocolMessage_ECHO_FROM_PROCESS  ReliableProtocolMessage_Stage = 2
	ReliableProtocolMessage_READY_FROM_WITNESS ReliableProtocolMessage_Stage = 3
	ReliableProtocolMessage_READY_FROM_PROCESS ReliableProtocolMessage_Stage = 4
	ReliableProtocolMessage_VALIDATE           ReliableProtocolMessage_Stage = 5
)

// Enum value maps for ReliableProtocolMessage_Stage.
var (
	ReliableProtocolMessage_Stage_name = map[int32]string{
		0: "NOTIFY",
		1: "ECHO_FROM_WITNESS",
		2: "ECHO_FROM_PROCESS",
		3: "READY_FROM_WITNESS",
		4: "READY_FROM_PROCESS",
		5: "VALIDATE",
	}
	ReliableProtocolMessage_Stage_value = map[string]int32{
		"NOTIFY":             0,
		"ECHO_FROM_WITNESS":  1,
		"ECHO_FROM_PROCESS":  2,
		"READY_FROM_WITNESS": 3,
		"READY_FROM_PROCESS": 4,
		"VALIDATE":           5,
	}
)

func (x ReliableProtocolMessage_Stage) Enum() *ReliableProtocolMessage_Stage {
	p := new(ReliableProtocolMessage_Stage)
	*p = x
	return p
}

func (x ReliableProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReliableProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[2].Descriptor()
}

func (ReliableProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[2]
}

func (x ReliableProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReliableProtocolMessage_Stage.Descriptor instead.
func (ReliableProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6, 0}
}

type RecoveryMessage_Stage int32

const (
	RecoveryMessage_RECOVER RecoveryMessage_Stage = 0
	RecoveryMessage_REPLY   RecoveryMessage_Stage = 1
	RecoveryMessage_ECHO    RecoveryMessage_Stage = 2
	RecoveryMessage_READY   RecoveryMessage_Stage = 3
)

// Enum value maps for RecoveryMessage_Stage.
var (
	RecoveryMessage_Stage_name = map[int32]string{
		0: "RECOVER",
		1: "REPLY",
		2: "ECHO",
		3: "READY",
	}
	RecoveryMessage_Stage_value = map[string]int32{
		"RECOVER": 0,
		"REPLY":   1,
		"ECHO":    2,
		"READY":   3,
	}
)

func (x RecoveryMessage_Stage) Enum() *RecoveryMessage_Stage {
	p := new(RecoveryMessage_Stage)
	*p = x
	return p
}

func (x RecoveryMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[3].Descriptor()
}

func (RecoveryMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[3]
}

func (x RecoveryMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryMessage_Stage.Descriptor instead.
func (RecoveryMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7, 0}
}

type ScalableProtocolMessage_Stage int32

const (
	ScalableProtocolMessage_GOSSIP           ScalableProtocolMessage_Stage = 0
	ScalableProtocolMessage_GOSSIP_SUBSCRIBE ScalableProtocolMessage_Stage = 1
	ScalableProtocolMessage_ECHO             ScalableProtocolMessage_Stage = 2
	ScalableProtocolMessage_ECHO_SUBSCRIBE   ScalableProtocolMessage_Stage = 3
	ScalableProtocolMessage_READY            ScalableProtocolMessage_Stage = 4
	ScalableProtocolMessage_READY_SUBSCRIBE  ScalableProtocolMessage_Stage = 5
)

// Enum value maps for ScalableProtocolMessage_Stage.
var (
	ScalableProtocolMessage_Stage_name = map[int32]string{
		0: "GOSSIP",
		1: "GOSSIP_SUBSCRIBE",
		2: "ECHO",
		3: "ECHO_SUBSCRIBE",
		4: "READY",
		5: "READY_SUBSCRIBE",
	}
	ScalableProtocolMessage_Stage_value = map[string]int32{
		"GOSSIP":           0,
		"GOSSIP_SUBSCRIBE": 1,
		"ECHO":             2,
		"ECHO_SUBSCRIBE":   3,
		"READY":            4,
		"READY_SUBSCRIBE":  5,
	}
)

func (x ScalableProtocolMessage_Stage) Enum() *ScalableProtocolMessage_Stage {
	p := new(ScalableProtocolMessage_Stage)
	*p = x
	return p
}

func (x ScalableProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalableProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[4].Descriptor()
}

func (ScalableProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[4]
}

func (x ScalableProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalableProtocolMessage_Stage.Descriptor instead.
func (ScalableProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8, 0}
}

type Started struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Started) Reset() {
	*x = Started{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Broadcast) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FaultyBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 int64 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 int64 `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *FaultyBroadcast) Reset() {
	*x = FaultyBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaultyBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultyBroadcast) ProtoMessage() {}

func (x *FaultyBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultyBroadcast.ProtoReflect.Descriptor instead.
func (*FaultyBroadcast) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *FaultyBroadcast) GetValue1() int64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *FaultyBroadcast) GetValue2() int64 {
	if x != nil {
		return x.Value2
	}
	return 0
}

type MessageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     int64  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	SeqNumber int64  `protobuf:"varint,2,opt,name=seqNumber,proto3" json:"seqNumber,omitempty"`
	Author    string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MessageData) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MessageData) GetSeqNumber() int64 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *MessageData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type BrachaMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage       BrachaMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.BrachaMessage_Stage" json:"stage,omitempty"`
	MessageData *MessageData        `protobuf:"bytes,2,opt,name=messageData,proto3" json:"messageData,omitempty"`
}

func (x *BrachaMessage) Reset() {
	*x = BrachaMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrachaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrachaMessage) ProtoMessage() {}

func (x *BrachaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrachaMessage.ProtoReflect.Descriptor instead.
func (*BrachaMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *BrachaMessage) GetStage() BrachaMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return BrachaMessage_INITIAL
}

func (x *BrachaMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

type ConsistentProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage       ConsistentProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ConsistentProtocolMessage_Stage" json:"stage,omitempty"`
	MessageData *MessageData                    `protobuf:"bytes,2,opt,name=messageData,proto3" json:"messageData,omitempty"`
}

func (x *ConsistentProtocolMessage) Reset() {
	*x = ConsistentProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsistentProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistentProtocolMessage) ProtoMessage() {}

func (x *ConsistentProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistentProtocolMessage.ProtoReflect.Descriptor instead.
func (*ConsistentProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ConsistentProtocolMessage) GetStage() ConsistentProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ConsistentProtocolMessage_ECHO
}

func (x *ConsistentProtocolMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

type ReliableProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage       ReliableProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ReliableProtocolMessage_Stage" json:"stage,omitempty"`
	MessageData *MessageData                  `protobuf:"bytes,2,opt,name=messageData,proto3" json:"messageData,omitempty"`
}

func (x *ReliableProtocolMessage) Reset() {
	*x = ReliableProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReliableProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliableProtocolMessage) ProtoMessage() {}

func (x *ReliableProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliableProtocolMessage.ProtoReflect.Descriptor instead.
func (*ReliableProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ReliableProtocolMessage) GetStage() ReliableProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ReliableProtocolMessage_NOTIFY
}

func (x *ReliableProtocolMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

type RecoveryMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecoveryStage RecoveryMessage_Stage    `protobuf:"varint,1,opt,name=recoveryStage,proto3,enum=messages.RecoveryMessage_Stage" json:"recoveryStage,omitempty"`
	Message       *ReliableProtocolMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RecoveryMessage) Reset() {
	*x = RecoveryMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryMessage) ProtoMessage() {}

func (x *RecoveryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryMessage.ProtoReflect.Descriptor instead.
func (*RecoveryMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RecoveryMessage) GetRecoveryStage() RecoveryMessage_Stage {
	if x != nil {
		return x.RecoveryStage
	}
	return RecoveryMessage_RECOVER
}

func (x *RecoveryMessage) GetMessage() *ReliableProtocolMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ScalableProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage       ScalableProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ScalableProtocolMessage_Stage" json:"stage,omitempty"`
	MessageData *MessageData                  `protobuf:"bytes,2,opt,name=messageData,proto3" json:"messageData,omitempty"`
}

func (x *ScalableProtocolMessage) Reset() {
	*x = ScalableProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalableProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalableProtocolMessage) ProtoMessage() {}

func (x *ScalableProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalableProtocolMessage.ProtoReflect.Descriptor instead.
func (*ScalableProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ScalableProtocolMessage) GetStage() ScalableProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ScalableProtocolMessage_GOSSIP
}

func (x *ScalableProtocolMessage) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x0f, 0x46, 0x61, 0x75, 0x6c,
	0x74, 0x79, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x59, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0xa8, 0x01, 0x0a, 0x0d, 0x42, 0x72, 0x61, 0x63, 0x68,
	0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x42, 0x72, 0x61, 0x63, 0x68, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x45, 0x43, 0x48, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10,
	0x02, 0x22, 0xb4, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1d, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x10, 0x01, 0x22, 0x92, 0x02, 0x0a, 0x17, 0x52, 0x65, 0x6c,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7f, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x57,
	0x49, 0x54, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x43, 0x48, 0x4f,
	0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12,
	0x16, 0x0a, 0x12, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x57, 0x49,
	0x54, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10, 0x04, 0x12,
	0x0c, 0x0a, 0x08, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x10, 0x05, 0x22, 0xcb, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x45, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x45, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x45, 0x50, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x22, 0xfa, 0x01, 0x0a, 0x17,
	0x53, 0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x67, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x53, 0x53,
	0x49, 0x50, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x4f, 0x53, 0x53, 0x49, 0x50, 0x5f, 0x53,
	0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43,
	0x48, 0x4f, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x53, 0x55, 0x42,
	0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x53, 0x55, 0x42,
	0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x05, 0x42, 0x2e, 0x5a, 0x2c, 0x73, 0x74, 0x6f, 0x63,
	0x68, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messages_proto_goTypes = []interface{}{
	(BrachaMessage_Stage)(0),             // 0: messages.BrachaMessage.Stage
	(ConsistentProtocolMessage_Stage)(0), // 1: messages.ConsistentProtocolMessage.Stage
	(ReliableProtocolMessage_Stage)(0),   // 2: messages.ReliableProtocolMessage.Stage
	(RecoveryMessage_Stage)(0),           // 3: messages.RecoveryMessage.Stage
	(ScalableProtocolMessage_Stage)(0),   // 4: messages.ScalableProtocolMessage.Stage
	(*Started)(nil),                      // 5: messages.Started
	(*Broadcast)(nil),                    // 6: messages.Broadcast
	(*FaultyBroadcast)(nil),              // 7: messages.FaultyBroadcast
	(*MessageData)(nil),                  // 8: messages.MessageData
	(*BrachaMessage)(nil),                // 9: messages.BrachaMessage
	(*ConsistentProtocolMessage)(nil),    // 10: messages.ConsistentProtocolMessage
	(*ReliableProtocolMessage)(nil),      // 11: messages.ReliableProtocolMessage
	(*RecoveryMessage)(nil),              // 12: messages.RecoveryMessage
	(*ScalableProtocolMessage)(nil),      // 13: messages.ScalableProtocolMessage
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: messages.BrachaMessage.stage:type_name -> messages.BrachaMessage.Stage
	8,  // 1: messages.BrachaMessage.messageData:type_name -> messages.MessageData
	1,  // 2: messages.ConsistentProtocolMessage.stage:type_name -> messages.ConsistentProtocolMessage.Stage
	8,  // 3: messages.ConsistentProtocolMessage.messageData:type_name -> messages.MessageData
	2,  // 4: messages.ReliableProtocolMessage.stage:type_name -> messages.ReliableProtocolMessage.Stage
	8,  // 5: messages.ReliableProtocolMessage.messageData:type_name -> messages.MessageData
	3,  // 6: messages.RecoveryMessage.recoveryStage:type_name -> messages.RecoveryMessage.Stage
	11, // 7: messages.RecoveryMessage.message:type_name -> messages.ReliableProtocolMessage
	4,  // 8: messages.ScalableProtocolMessage.stage:type_name -> messages.ScalableProtocolMessage.Stage
	8,  // 9: messages.ScalableProtocolMessage.messageData:type_name -> messages.MessageData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Started); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaultyBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrachaMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsistentProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReliableProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalableProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
