// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrachaProtocolMessage_Stage int32

const (
	BrachaProtocolMessage_INITIAL BrachaProtocolMessage_Stage = 0
	BrachaProtocolMessage_ECHO    BrachaProtocolMessage_Stage = 1
	BrachaProtocolMessage_READY   BrachaProtocolMessage_Stage = 2
)

// Enum value maps for BrachaProtocolMessage_Stage.
var (
	BrachaProtocolMessage_Stage_name = map[int32]string{
		0: "INITIAL",
		1: "ECHO",
		2: "READY",
	}
	BrachaProtocolMessage_Stage_value = map[string]int32{
		"INITIAL": 0,
		"ECHO":    1,
		"READY":   2,
	}
)

func (x BrachaProtocolMessage_Stage) Enum() *BrachaProtocolMessage_Stage {
	p := new(BrachaProtocolMessage_Stage)
	*p = x
	return p
}

func (x BrachaProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrachaProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (BrachaProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x BrachaProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrachaProtocolMessage_Stage.Descriptor instead.
func (BrachaProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7, 0}
}

type ConsistentProtocolMessage_Stage int32

const (
	ConsistentProtocolMessage_ECHO   ConsistentProtocolMessage_Stage = 0
	ConsistentProtocolMessage_VERIFY ConsistentProtocolMessage_Stage = 1
)

// Enum value maps for ConsistentProtocolMessage_Stage.
var (
	ConsistentProtocolMessage_Stage_name = map[int32]string{
		0: "ECHO",
		1: "VERIFY",
	}
	ConsistentProtocolMessage_Stage_value = map[string]int32{
		"ECHO":   0,
		"VERIFY": 1,
	}
)

func (x ConsistentProtocolMessage_Stage) Enum() *ConsistentProtocolMessage_Stage {
	p := new(ConsistentProtocolMessage_Stage)
	*p = x
	return p
}

func (x ConsistentProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistentProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ConsistentProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ConsistentProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistentProtocolMessage_Stage.Descriptor instead.
func (ConsistentProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8, 0}
}

type ReliableProtocolMessage_Stage int32

const (
	ReliableProtocolMessage_NOTIFY             ReliableProtocolMessage_Stage = 0
	ReliableProtocolMessage_ECHO_FROM_WITNESS  ReliableProtocolMessage_Stage = 1
	ReliableProtocolMessage_ECHO_FROM_PROCESS  ReliableProtocolMessage_Stage = 2
	ReliableProtocolMessage_READY_FROM_WITNESS ReliableProtocolMessage_Stage = 3
	ReliableProtocolMessage_READY_FROM_PROCESS ReliableProtocolMessage_Stage = 4
	ReliableProtocolMessage_VALIDATE           ReliableProtocolMessage_Stage = 5
)

// Enum value maps for ReliableProtocolMessage_Stage.
var (
	ReliableProtocolMessage_Stage_name = map[int32]string{
		0: "NOTIFY",
		1: "ECHO_FROM_WITNESS",
		2: "ECHO_FROM_PROCESS",
		3: "READY_FROM_WITNESS",
		4: "READY_FROM_PROCESS",
		5: "VALIDATE",
	}
	ReliableProtocolMessage_Stage_value = map[string]int32{
		"NOTIFY":             0,
		"ECHO_FROM_WITNESS":  1,
		"ECHO_FROM_PROCESS":  2,
		"READY_FROM_WITNESS": 3,
		"READY_FROM_PROCESS": 4,
		"VALIDATE":           5,
	}
)

func (x ReliableProtocolMessage_Stage) Enum() *ReliableProtocolMessage_Stage {
	p := new(ReliableProtocolMessage_Stage)
	*p = x
	return p
}

func (x ReliableProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReliableProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[2].Descriptor()
}

func (ReliableProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[2]
}

func (x ReliableProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReliableProtocolMessage_Stage.Descriptor instead.
func (ReliableProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9, 0}
}

type RecoveryProtocolMessage_Stage int32

const (
	RecoveryProtocolMessage_RECOVER RecoveryProtocolMessage_Stage = 0
	RecoveryProtocolMessage_REPLY   RecoveryProtocolMessage_Stage = 1
	RecoveryProtocolMessage_ECHO    RecoveryProtocolMessage_Stage = 2
	RecoveryProtocolMessage_READY   RecoveryProtocolMessage_Stage = 3
)

// Enum value maps for RecoveryProtocolMessage_Stage.
var (
	RecoveryProtocolMessage_Stage_name = map[int32]string{
		0: "RECOVER",
		1: "REPLY",
		2: "ECHO",
		3: "READY",
	}
	RecoveryProtocolMessage_Stage_value = map[string]int32{
		"RECOVER": 0,
		"REPLY":   1,
		"ECHO":    2,
		"READY":   3,
	}
)

func (x RecoveryProtocolMessage_Stage) Enum() *RecoveryProtocolMessage_Stage {
	p := new(RecoveryProtocolMessage_Stage)
	*p = x
	return p
}

func (x RecoveryProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[3].Descriptor()
}

func (RecoveryProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[3]
}

func (x RecoveryProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryProtocolMessage_Stage.Descriptor instead.
func (RecoveryProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10, 0}
}

type ScalableProtocolMessage_Stage int32

const (
	ScalableProtocolMessage_GOSSIP           ScalableProtocolMessage_Stage = 0
	ScalableProtocolMessage_GOSSIP_SUBSCRIBE ScalableProtocolMessage_Stage = 1
	ScalableProtocolMessage_ECHO             ScalableProtocolMessage_Stage = 2
	ScalableProtocolMessage_ECHO_SUBSCRIBE   ScalableProtocolMessage_Stage = 3
	ScalableProtocolMessage_READY            ScalableProtocolMessage_Stage = 4
	ScalableProtocolMessage_READY_SUBSCRIBE  ScalableProtocolMessage_Stage = 5
)

// Enum value maps for ScalableProtocolMessage_Stage.
var (
	ScalableProtocolMessage_Stage_name = map[int32]string{
		0: "GOSSIP",
		1: "GOSSIP_SUBSCRIBE",
		2: "ECHO",
		3: "ECHO_SUBSCRIBE",
		4: "READY",
		5: "READY_SUBSCRIBE",
	}
	ScalableProtocolMessage_Stage_value = map[string]int32{
		"GOSSIP":           0,
		"GOSSIP_SUBSCRIBE": 1,
		"ECHO":             2,
		"ECHO_SUBSCRIBE":   3,
		"READY":            4,
		"READY_SUBSCRIBE":  5,
	}
)

func (x ScalableProtocolMessage_Stage) Enum() *ScalableProtocolMessage_Stage {
	p := new(ScalableProtocolMessage_Stage)
	*p = x
	return p
}

func (x ScalableProtocolMessage_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalableProtocolMessage_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[4].Descriptor()
}

func (ScalableProtocolMessage_Stage) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[4]
}

func (x ScalableProtocolMessage_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalableProtocolMessage_Stage.Descriptor instead.
func (ScalableProtocolMessage_Stage) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11, 0}
}

type ConnMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Stub int64 `protobuf:"varint,2,opt,name=stub,proto3" json:"stub,omitempty"`
}

func (x *ConnMessage) Reset() {
	*x = ConnMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMessage) ProtoMessage() {}

func (x *ConnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMessage.ProtoReflect.Descriptor instead.
func (*ConnMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConnMessage) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ConnMessage) GetStub() int64 {
	if x != nil {
		return x.Stub
	}
	return 0
}

type Greet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Stub int64 `protobuf:"varint,3,opt,name=stub,proto3" json:"stub,omitempty"`
}

func (x *Greet) Reset() {
	*x = Greet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greet) ProtoMessage() {}

func (x *Greet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greet.ProtoReflect.Descriptor instead.
func (*Greet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Greet) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Greet) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Greet) GetStub() int64 {
	if x != nil {
		return x.Stub
	}
	return 0
}

type Started struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Started) Reset() {
	*x = Started{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

type Simulate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Simulate) Reset() {
	*x = Simulate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Simulate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simulate) ProtoMessage() {}

func (x *Simulate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simulate.ProtoReflect.Descriptor instead.
func (*Simulate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

type Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Broadcast) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender int64 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Stamp  int64 `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Ack) GetStamp() int64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

type BroadcastInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author    int64 `protobuf:"varint,1,opt,name=author,proto3" json:"author,omitempty"`
	SeqNumber int64 `protobuf:"varint,2,opt,name=seqNumber,proto3" json:"seqNumber,omitempty"`
}

func (x *BroadcastInstance) Reset() {
	*x = BroadcastInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastInstance) ProtoMessage() {}

func (x *BroadcastInstance) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastInstance.ProtoReflect.Descriptor instead.
func (*BroadcastInstance) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastInstance) GetAuthor() int64 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *BroadcastInstance) GetSeqNumber() int64 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

type BrachaProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage BrachaProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.BrachaProtocolMessage_Stage" json:"stage,omitempty"`
	Value int64                       `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BrachaProtocolMessage) Reset() {
	*x = BrachaProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrachaProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrachaProtocolMessage) ProtoMessage() {}

func (x *BrachaProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrachaProtocolMessage.ProtoReflect.Descriptor instead.
func (*BrachaProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BrachaProtocolMessage) GetStage() BrachaProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return BrachaProtocolMessage_INITIAL
}

func (x *BrachaProtocolMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ConsistentProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage ConsistentProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ConsistentProtocolMessage_Stage" json:"stage,omitempty"`
	Value int64                           `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConsistentProtocolMessage) Reset() {
	*x = ConsistentProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsistentProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistentProtocolMessage) ProtoMessage() {}

func (x *ConsistentProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistentProtocolMessage.ProtoReflect.Descriptor instead.
func (*ConsistentProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ConsistentProtocolMessage) GetStage() ConsistentProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ConsistentProtocolMessage_ECHO
}

func (x *ConsistentProtocolMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ReliableProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage ReliableProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ReliableProtocolMessage_Stage" json:"stage,omitempty"`
	Value int64                         `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReliableProtocolMessage) Reset() {
	*x = ReliableProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReliableProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReliableProtocolMessage) ProtoMessage() {}

func (x *ReliableProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReliableProtocolMessage.ProtoReflect.Descriptor instead.
func (*ReliableProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReliableProtocolMessage) GetStage() ReliableProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ReliableProtocolMessage_NOTIFY
}

func (x *ReliableProtocolMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RecoveryProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage                   RecoveryProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.RecoveryProtocolMessage_Stage" json:"stage,omitempty"`
	ReliableProtocolMessage *ReliableProtocolMessage      `protobuf:"bytes,2,opt,name=reliableProtocolMessage,proto3" json:"reliableProtocolMessage,omitempty"`
}

func (x *RecoveryProtocolMessage) Reset() {
	*x = RecoveryProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryProtocolMessage) ProtoMessage() {}

func (x *RecoveryProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryProtocolMessage.ProtoReflect.Descriptor instead.
func (*RecoveryProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RecoveryProtocolMessage) GetStage() RecoveryProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return RecoveryProtocolMessage_RECOVER
}

func (x *RecoveryProtocolMessage) GetReliableProtocolMessage() *ReliableProtocolMessage {
	if x != nil {
		return x.ReliableProtocolMessage
	}
	return nil
}

type ScalableProtocolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage ScalableProtocolMessage_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=messages.ScalableProtocolMessage_Stage" json:"stage,omitempty"`
	Value int64                         `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ScalableProtocolMessage) Reset() {
	*x = ScalableProtocolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalableProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalableProtocolMessage) ProtoMessage() {}

func (x *ScalableProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalableProtocolMessage.ProtoReflect.Descriptor instead.
func (*ScalableProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ScalableProtocolMessage) GetStage() ScalableProtocolMessage_Stage {
	if x != nil {
		return x.Stage
	}
	return ScalableProtocolMessage_GOSSIP
}

func (x *ScalableProtocolMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BroadcastInstanceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BroadcastInstance *BroadcastInstance `protobuf:"bytes,1,opt,name=broadcastInstance,proto3" json:"broadcastInstance,omitempty"`
	// Types that are assignable to Message:
	//
	//	*BroadcastInstanceMessage_BrachaProtocolMessage
	//	*BroadcastInstanceMessage_ConsistentProtocolMessage
	//	*BroadcastInstanceMessage_ReliableProtocolMessage
	//	*BroadcastInstanceMessage_RecoveryProtocolMessage
	//	*BroadcastInstanceMessage_ScalableProtocolMessage
	Message isBroadcastInstanceMessage_Message `protobuf_oneof:"message"`
}

func (x *BroadcastInstanceMessage) Reset() {
	*x = BroadcastInstanceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastInstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastInstanceMessage) ProtoMessage() {}

func (x *BroadcastInstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastInstanceMessage.ProtoReflect.Descriptor instead.
func (*BroadcastInstanceMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastInstanceMessage) GetBroadcastInstance() *BroadcastInstance {
	if x != nil {
		return x.BroadcastInstance
	}
	return nil
}

func (m *BroadcastInstanceMessage) GetMessage() isBroadcastInstanceMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *BroadcastInstanceMessage) GetBrachaProtocolMessage() *BrachaProtocolMessage {
	if x, ok := x.GetMessage().(*BroadcastInstanceMessage_BrachaProtocolMessage); ok {
		return x.BrachaProtocolMessage
	}
	return nil
}

func (x *BroadcastInstanceMessage) GetConsistentProtocolMessage() *ConsistentProtocolMessage {
	if x, ok := x.GetMessage().(*BroadcastInstanceMessage_ConsistentProtocolMessage); ok {
		return x.ConsistentProtocolMessage
	}
	return nil
}

func (x *BroadcastInstanceMessage) GetReliableProtocolMessage() *ReliableProtocolMessage {
	if x, ok := x.GetMessage().(*BroadcastInstanceMessage_ReliableProtocolMessage); ok {
		return x.ReliableProtocolMessage
	}
	return nil
}

func (x *BroadcastInstanceMessage) GetRecoveryProtocolMessage() *RecoveryProtocolMessage {
	if x, ok := x.GetMessage().(*BroadcastInstanceMessage_RecoveryProtocolMessage); ok {
		return x.RecoveryProtocolMessage
	}
	return nil
}

func (x *BroadcastInstanceMessage) GetScalableProtocolMessage() *ScalableProtocolMessage {
	if x, ok := x.GetMessage().(*BroadcastInstanceMessage_ScalableProtocolMessage); ok {
		return x.ScalableProtocolMessage
	}
	return nil
}

type isBroadcastInstanceMessage_Message interface {
	isBroadcastInstanceMessage_Message()
}

type BroadcastInstanceMessage_BrachaProtocolMessage struct {
	BrachaProtocolMessage *BrachaProtocolMessage `protobuf:"bytes,4,opt,name=brachaProtocolMessage,proto3,oneof"`
}

type BroadcastInstanceMessage_ConsistentProtocolMessage struct {
	ConsistentProtocolMessage *ConsistentProtocolMessage `protobuf:"bytes,5,opt,name=consistentProtocolMessage,proto3,oneof"`
}

type BroadcastInstanceMessage_ReliableProtocolMessage struct {
	ReliableProtocolMessage *ReliableProtocolMessage `protobuf:"bytes,6,opt,name=reliableProtocolMessage,proto3,oneof"`
}

type BroadcastInstanceMessage_RecoveryProtocolMessage struct {
	RecoveryProtocolMessage *RecoveryProtocolMessage `protobuf:"bytes,7,opt,name=recoveryProtocolMessage,proto3,oneof"`
}

type BroadcastInstanceMessage_ScalableProtocolMessage struct {
	ScalableProtocolMessage *ScalableProtocolMessage `protobuf:"bytes,8,opt,name=scalableProtocolMessage,proto3,oneof"`
}

func (*BroadcastInstanceMessage_BrachaProtocolMessage) isBroadcastInstanceMessage_Message() {}

func (*BroadcastInstanceMessage_ConsistentProtocolMessage) isBroadcastInstanceMessage_Message() {}

func (*BroadcastInstanceMessage_ReliableProtocolMessage) isBroadcastInstanceMessage_Message() {}

func (*BroadcastInstanceMessage_RecoveryProtocolMessage) isBroadcastInstanceMessage_Message() {}

func (*BroadcastInstanceMessage_ScalableProtocolMessage) isBroadcastInstanceMessage_Message() {}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender int64 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Stamp  int64 `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	// Types that are assignable to Content:
	//
	//	*Message_Started
	//	*Message_Simulate
	//	*Message_BroadcastInstanceMessage
	//	*Message_Ack
	//	*Message_Broadcast
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Message) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetStamp() int64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Message) GetStarted() *Started {
	if x, ok := x.GetContent().(*Message_Started); ok {
		return x.Started
	}
	return nil
}

func (x *Message) GetSimulate() *Simulate {
	if x, ok := x.GetContent().(*Message_Simulate); ok {
		return x.Simulate
	}
	return nil
}

func (x *Message) GetBroadcastInstanceMessage() *BroadcastInstanceMessage {
	if x, ok := x.GetContent().(*Message_BroadcastInstanceMessage); ok {
		return x.BroadcastInstanceMessage
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x, ok := x.GetContent().(*Message_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *Message) GetBroadcast() *Broadcast {
	if x, ok := x.GetContent().(*Message_Broadcast); ok {
		return x.Broadcast
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Started struct {
	Started *Started `protobuf:"bytes,3,opt,name=started,proto3,oneof"`
}

type Message_Simulate struct {
	Simulate *Simulate `protobuf:"bytes,4,opt,name=simulate,proto3,oneof"`
}

type Message_BroadcastInstanceMessage struct {
	BroadcastInstanceMessage *BroadcastInstanceMessage `protobuf:"bytes,5,opt,name=broadcastInstanceMessage,proto3,oneof"`
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type Message_Broadcast struct {
	Broadcast *Broadcast `protobuf:"bytes,7,opt,name=broadcast,proto3,oneof"`
}

func (*Message_Started) isMessage_Content() {}

func (*Message_Simulate) isMessage_Content() {}

func (*Message_BroadcastInstanceMessage) isMessage_Content() {}

func (*Message_Ack) isMessage_Content() {}

func (*Message_Broadcast) isMessage_Content() {}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x75,
	0x62, 0x22, 0x3f, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x74, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74,
	0x75, 0x62, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x0a, 0x0a,
	0x08, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x03,
	0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x49, 0x0a, 0x11, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x95, 0x01, 0x0a,
	0x15, 0x42, 0x72, 0x61, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x42, 0x72, 0x61, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41,
	0x44, 0x59, 0x10, 0x02, 0x22, 0x91, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x3f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x29, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x10, 0x01, 0x22, 0xef, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x6c,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7f, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x57, 0x49, 0x54, 0x4e,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x46, 0x52,
	0x4f, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x5f, 0x57, 0x49, 0x54, 0x4e, 0x45,
	0x53, 0x53, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x46, 0x52,
	0x4f, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x10, 0x05, 0x22, 0xeb, 0x01, 0x0a, 0x17, 0x52,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x5b, 0x0a, 0x17, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x17, 0x72, 0x65, 0x6c, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x50, 0x4c,
	0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x22, 0xd7, 0x01, 0x0a, 0x17, 0x53, 0x63, 0x61,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53,
	0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x67, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x53, 0x53, 0x49, 0x50, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x47, 0x4f, 0x53, 0x53, 0x49, 0x50, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49,
	0x42, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43, 0x48, 0x4f, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x04, 0x12, 0x13, 0x0a,
	0x0f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45,
	0x10, 0x05, 0x22, 0xcb, 0x04, 0x0a, 0x18, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x49, 0x0a, 0x11, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x11, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x15, 0x62, 0x72,
	0x61, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x72, 0x61, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x15, 0x62, 0x72,
	0x61, 0x63, 0x68, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x63, 0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x19, 0x63,
	0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x17, 0x72, 0x65, 0x6c, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x17,
	0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x17, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x17, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x17, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x17, 0x73, 0x63,
	0x61, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xdd, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x73, 0x69, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x60, 0x0a, 0x18, 0x62,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x18, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b,
	0x12, 0x33, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x42, 0x2e, 0x5a, 0x2c, 0x73, 0x74, 0x6f, 0x63, 0x68, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2d, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_messages_proto_goTypes = []interface{}{
	(BrachaProtocolMessage_Stage)(0),     // 0: messages.BrachaProtocolMessage.Stage
	(ConsistentProtocolMessage_Stage)(0), // 1: messages.ConsistentProtocolMessage.Stage
	(ReliableProtocolMessage_Stage)(0),   // 2: messages.ReliableProtocolMessage.Stage
	(RecoveryProtocolMessage_Stage)(0),   // 3: messages.RecoveryProtocolMessage.Stage
	(ScalableProtocolMessage_Stage)(0),   // 4: messages.ScalableProtocolMessage.Stage
	(*ConnMessage)(nil),                  // 5: messages.ConnMessage
	(*Greet)(nil),                        // 6: messages.Greet
	(*Started)(nil),                      // 7: messages.Started
	(*Simulate)(nil),                     // 8: messages.Simulate
	(*Broadcast)(nil),                    // 9: messages.Broadcast
	(*Ack)(nil),                          // 10: messages.Ack
	(*BroadcastInstance)(nil),            // 11: messages.BroadcastInstance
	(*BrachaProtocolMessage)(nil),        // 12: messages.BrachaProtocolMessage
	(*ConsistentProtocolMessage)(nil),    // 13: messages.ConsistentProtocolMessage
	(*ReliableProtocolMessage)(nil),      // 14: messages.ReliableProtocolMessage
	(*RecoveryProtocolMessage)(nil),      // 15: messages.RecoveryProtocolMessage
	(*ScalableProtocolMessage)(nil),      // 16: messages.ScalableProtocolMessage
	(*BroadcastInstanceMessage)(nil),     // 17: messages.BroadcastInstanceMessage
	(*Message)(nil),                      // 18: messages.Message
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: messages.BrachaProtocolMessage.stage:type_name -> messages.BrachaProtocolMessage.Stage
	1,  // 1: messages.ConsistentProtocolMessage.stage:type_name -> messages.ConsistentProtocolMessage.Stage
	2,  // 2: messages.ReliableProtocolMessage.stage:type_name -> messages.ReliableProtocolMessage.Stage
	3,  // 3: messages.RecoveryProtocolMessage.stage:type_name -> messages.RecoveryProtocolMessage.Stage
	14, // 4: messages.RecoveryProtocolMessage.reliableProtocolMessage:type_name -> messages.ReliableProtocolMessage
	4,  // 5: messages.ScalableProtocolMessage.stage:type_name -> messages.ScalableProtocolMessage.Stage
	11, // 6: messages.BroadcastInstanceMessage.broadcastInstance:type_name -> messages.BroadcastInstance
	12, // 7: messages.BroadcastInstanceMessage.brachaProtocolMessage:type_name -> messages.BrachaProtocolMessage
	13, // 8: messages.BroadcastInstanceMessage.consistentProtocolMessage:type_name -> messages.ConsistentProtocolMessage
	14, // 9: messages.BroadcastInstanceMessage.reliableProtocolMessage:type_name -> messages.ReliableProtocolMessage
	15, // 10: messages.BroadcastInstanceMessage.recoveryProtocolMessage:type_name -> messages.RecoveryProtocolMessage
	16, // 11: messages.BroadcastInstanceMessage.scalableProtocolMessage:type_name -> messages.ScalableProtocolMessage
	7,  // 12: messages.Message.started:type_name -> messages.Started
	8,  // 13: messages.Message.simulate:type_name -> messages.Simulate
	17, // 14: messages.Message.broadcastInstanceMessage:type_name -> messages.BroadcastInstanceMessage
	10, // 15: messages.Message.ack:type_name -> messages.Ack
	9,  // 16: messages.Message.broadcast:type_name -> messages.Broadcast
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Started); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Simulate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrachaProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsistentProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReliableProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalableProtocolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastInstanceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*BroadcastInstanceMessage_BrachaProtocolMessage)(nil),
		(*BroadcastInstanceMessage_ConsistentProtocolMessage)(nil),
		(*BroadcastInstanceMessage_ReliableProtocolMessage)(nil),
		(*BroadcastInstanceMessage_RecoveryProtocolMessage)(nil),
		(*BroadcastInstanceMessage_ScalableProtocolMessage)(nil),
	}
	file_messages_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*Message_Started)(nil),
		(*Message_Simulate)(nil),
		(*Message_BroadcastInstanceMessage)(nil),
		(*Message_Ack)(nil),
		(*Message_Broadcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
